// <auto-generated />
using System;
using GameDevManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDevManager.Data.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GameDevManagerDbContext))]
    [Migration("20260807084251_Audio")]
    partial class Audio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GameDevManager.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("OwnerEntityId", "IsPrimary");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "Name")
                        .IsUnique();

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetTagId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId", "AssetTagId");

                    b.HasIndex("AssetTagId");

                    b.ToTable("AssetTagAssignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Collectible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Collectibles");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConditionSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConditionSetId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Logic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("OwnerId", "Slot")
                        .IsUnique();

                    b.ToTable("ConditionSets");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ContentTags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTagAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentTagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTagId");

                    b.HasIndex("TargetEntityId", "ContentTagId")
                        .IsUnique();

                    b.ToTable("ContentTagAssignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTagScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentTagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTagId");

                    b.ToTable("ContentTagScopes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "ModuleKey");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DialogueLineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NextLineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueLineId");

                    b.HasIndex("NextLineId");

                    b.ToTable("DialogueChoices");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DialogueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpeakerNpcId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.HasIndex("SpeakerNpcId");

                    b.ToTable("DialogueLines");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DialogueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.HasIndex("NpcId");

                    b.ToTable("DialogueParticipants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DiplomaticRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FactionAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FactionBId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("FactionAId");

                    b.HasIndex("FactionBId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("DiplomaticRelations");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.EffectAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameEffectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameEffectId");

                    b.HasIndex("ItemId");

                    b.ToTable("EffectAssignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.EventSpawn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameEventId");

                    b.HasIndex("NpcId");

                    b.ToTable("EventSpawns");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FactionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("NpcId");

                    b.ToTable("FactionMembers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("OwnerEntityId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.ToTable("FieldOptions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ReferenceValue");

                    b.HasIndex("OwnerEntityId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("GameEffects");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Chance")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RewardLootTableId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("RewardLootTableId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameProjects");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Chance")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootEntries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RollMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("LootTables");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.MapMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IconAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Radius")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("MapMarkers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterClassId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuestGiver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("IsTrader");

                    b.HasIndex("LootTableId");

                    b.HasIndex("Name");

                    b.HasIndex("GameProjectId", "Kind");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterClassId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("GameProjectId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DialogueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GiverNpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StoryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("DialogueId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("GiverNpcId");

                    b.HasIndex("Name");

                    b.HasIndex("StoryEntryId");

                    b.HasIndex("GameProjectId", "Kind");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutputItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("OutputItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CostItemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CostItemId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CostPoints")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentSkillId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SkillTreeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("CostItemId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentSkillId");

                    b.HasIndex("SkillTreeId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.SkillTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.ToTable("SkillTrees");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.SoundEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("SoundEffects");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("GameProjectId", "SortOrder");

                    b.ToTable("StoryEntries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoryEntryId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("StoryParticipants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.TraderOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RestockSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("NpcId");

                    b.ToTable("TraderOffers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevManager.Domain.Entities.AssetTag", "Tag")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.CharacterClass", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Collectible", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Condition", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ConditionSet", "ConditionSet")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionSet");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTag", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTagAssignment", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentTag", "ContentTag")
                        .WithMany("Assignments")
                        .HasForeignKey("ContentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentTag");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTagScope", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentTag", "ContentTag")
                        .WithMany("Scopes")
                        .HasForeignKey("ContentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentTag");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Currency", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueChoice", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.DialogueLine", "Line")
                        .WithMany("Choices")
                        .HasForeignKey("DialogueLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Dialogue", "Dialogue")
                        .WithMany("Lines")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueParticipant", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Dialogue", "Dialogue")
                        .WithMany("Participants")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DiplomaticRelation", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.EffectAssignment", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameEffect", "GameEffect")
                        .WithMany("Assignments")
                        .HasForeignKey("GameEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEffect");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.EventSpawn", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameEvent", "GameEvent")
                        .WithMany("Spawns")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FactionMember", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Faction", "Faction")
                        .WithMany("Members")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEffect", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEvent", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootEntry", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.MapMarker", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameMap", "Map")
                        .WithMany("Markers")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Quest", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Skill", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.SkillTree", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.SoundEffect", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryParticipant", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.StoryEntry", "StoryEntry")
                        .WithMany("Participants")
                        .HasForeignKey("StoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoryEntry");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.TraderOffer", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Npc", "Npc")
                        .WithMany("Offers")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentTag", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEffect", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameEvent", b =>
                {
                    b.Navigation("Spawns");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.Navigation("Markers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
