// <auto-generated />
using System;
using GameDevManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDevManager.Data.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GameDevManagerDbContext))]
    [Migration("20260806200915_CraftingRecipes")]
    partial class CraftingRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("OwnerEntityId", "IsPrimary");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "Name")
                        .IsUnique();

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetTagId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId", "AssetTagId");

                    b.HasIndex("AssetTagId");

                    b.ToTable("AssetTagAssignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "ModuleKey");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("OwnerEntityId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.ToTable("FieldOptions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ReferenceValue");

                    b.HasIndex("OwnerEntityId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameProjects");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutputItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("OutputItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevManager.Domain.Entities.AssetTag", "Tag")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
