// <auto-generated />
using System;
using GameDevManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDevManager.Data.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(GameDevManagerDbContext))]
    [Migration("20260807072720_Quests")]
    partial class Quests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("OwnerEntityId", "IsPrimary");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "Name")
                        .IsUnique();

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetId", "AssetTagId");

                    b.HasIndex("AssetTagId");

                    b.ToTable("AssetTagAssignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<Guid>("ConditionSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("float");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionSetId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Logic")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("OwnerId", "Slot")
                        .IsUnique();

                    b.ToTable("ConditionSets");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameProjectId", "ModuleKey");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IncludesPlayer")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DialogueLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NextLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DialogueLineId");

                    b.HasIndex("NextLineId");

                    b.ToTable("DialogueChoices");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DialogueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("SpeakerNpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.HasIndex("SpeakerNpcId");

                    b.ToTable("DialogueLines");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DialogueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.HasIndex("NpcId");

                    b.ToTable("DialogueParticipants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DiplomaticRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("FactionAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactionBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stance")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("FactionAId");

                    b.HasIndex("FactionBId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("DiplomaticRelations");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FactionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("NpcId");

                    b.ToTable("FactionMembers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("OwnerEntityId");

                    b.ToTable("FieldDefinitions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.ToTable("FieldOptions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("float");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReferenceValue")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("ReferenceValue");

                    b.HasIndex("OwnerEntityId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GameProjects");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Chance")
                        .HasColumnType("float");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootEntries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RollMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.ToTable("LootTables");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.MapMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("IconAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Radius")
                        .HasColumnType("float");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("MapMarkers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsQuestGiver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrader")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("IsTrader");

                    b.HasIndex("LootTableId");

                    b.HasIndex("Name");

                    b.HasIndex("GameProjectId", "Kind");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("DialogueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GiverNpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StoryEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("DialogueId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("GiverNpcId");

                    b.HasIndex("Name");

                    b.HasIndex("StoryEntryId");

                    b.HasIndex("GameProjectId", "Kind");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OutputItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("OutputItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("GameProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("GameProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("GameProjectId", "SortOrder");

                    b.ToTable("StoryEntries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("StoryEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StoryEntryId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("StoryParticipants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.TraderOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("RestockSeconds")
                        .HasColumnType("float");

                    b.Property<double?>("SellPrice")
                        .HasColumnType("float");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("NpcId");

                    b.ToTable("TraderOffers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTagAssignment", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Asset", "Asset")
                        .WithMany("Tags")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevManager.Domain.Entities.AssetTag", "Tag")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Condition", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ConditionSet", "ConditionSet")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionSet");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Currency", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueChoice", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.DialogueLine", "Line")
                        .WithMany("Choices")
                        .HasForeignKey("DialogueLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Dialogue", "Dialogue")
                        .WithMany("Lines")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueParticipant", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Dialogue", "Dialogue")
                        .WithMany("Participants")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DiplomaticRelation", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FactionMember", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Faction", "Faction")
                        .WithMany("Members")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldOption", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldValue", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.FieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Item", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootEntry", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.MapMarker", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.GameMap", "Map")
                        .WithMany("Markers")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Quest", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameDevManager.Domain.Entities.GameProject", "GameProject")
                        .WithMany()
                        .HasForeignKey("GameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("GameProject");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryParticipant", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.StoryEntry", "StoryEntry")
                        .WithMany("Participants")
                        .HasForeignKey("StoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoryEntry");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.TraderOffer", b =>
                {
                    b.HasOne("GameDevManager.Domain.Entities.Npc", "Npc")
                        .WithMany("Offers")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.AssetTag", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ConditionSet", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.ContentType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Dialogue", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.DialogueLine", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Faction", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.FieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.GameMap", b =>
                {
                    b.Navigation("Markers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Npc", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("GameDevManager.Domain.Entities.StoryEntry", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
