<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\GameDevManager.Data\GameDevManager.Data.csproj" />
    <ProjectReference Include="..\GameDevManager.Data.Migrations.SqlServer\GameDevManager.Data.Migrations.SqlServer.csproj" />
    <ProjectReference Include="..\GameDevManager.Data.Migrations.PostgreSql\GameDevManager.Data.Migrations.PostgreSql.csproj" />
    <ProjectReference Include="..\GameDevManager.Data.Migrations.MySql\GameDevManager.Data.Migrations.MySql.csproj" />
    <ProjectReference Include="..\GameDevManager.Data.Migrations.Sqlite\GameDevManager.Data.Migrations.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="*" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
